<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
<entry key="Diad.fait.class.path">fait.jar:asm.jar:eclipsejar:junit.jar:ivy.jar:slf4j-api.jar</entry>
<entry key="Diad.seede.class.path">seede.jar:asm.jar:eclipsejar:junit.jar:ivy.jar:slf4j-api.jar:poppy.jar</entry>
<entry key="Diad.limba.class.path">limba.jar:eclipsejar:ivy.jar:junit.jar:asm.jar:json.jar</entry>
</properties>

















